###
@urlServer = http://localhost:4000

###
GET {{urlServer}}/events

###
POST {{urlServer}}/events
Content-Type: application/json

{
  "description": "Curso Spring JPA",
  "type": 4,
  "dateTime": "2025-12-20T18:00:00",
  "startingSales": "2025-12-10T20:00:00",
  "endingSales": "2025-12-19T23:59:59",
  "price": 1500
}

###
GET {{urlServer}}/sales

###
POST {{urlServer}}/sales
Content-Type: application/json

{
  "eventId": "ce37de40-de60-4835-b77b-e6370bc784b7",
  "userId": "92ff4138-3ae5-4282-a918-46a663c17629"
}

